apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: opennmt-openshift
    name: opennmt-openshift
  spec:
    ports:
    - name: 6006-tcp
      port: 6006
      protocol: TCP
      targetPort: 6006
    selector:
      app: opennmt-openshift
      deploymentconfig: opennmt-openshift
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: opennmt-openshift
    name: opennmt-openshift
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: opennmt-openshift
      deploymentconfig: opennmt-openshift
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: opennmt-openshift
          deploymentconfig: opennmt-openshift
      spec:
        volumes: 
          - persistentVolumeClaim:
              claimName: opennmt
            name: opennmt-storage
        containers:
        - args:
          - ./run.sh
          image: "opennmt-openshift:latest"
          env:
          - name: "RUN_MODE"
            value: "serve"
          imagePullPolicy: Always
          name: opennmt-openshift
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 6006
            protocol: TCP
            name: tensorboard
          resources:
            limits:
              cpu: "12"
              memory: 24Gi
              #nvidia.com/gpu: '4'
            requests:
              cpu: "12"
              memory: 24Gi
              #nvidia.com/gpu: '4'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts: 
            - mountPath: /opt/app-root/src/jabberwocky
              name: opennmt-storage
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - opennmt-openshift
        from:
          kind: ImageStreamTag
          name: opennmt-openshift:latest
      type: ImageChange
  status:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: opennmt-openshift
    name: opennmt-openshift
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: opennmt-openshift:latest
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/vpavlin/OpenNMT-openshift
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python-36-centos7:latest
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: DXhHfzBbWf7l8fLIGAfz
      type: GitHub
    - generic:
        secret: GiasoxKe1JGycv7F1wR3
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: centos/python-36-centos7@sha256:3be9885759261fc90b2bf155f199149f83ee78a58d4b40fdab8c97ae2875ba29
      type: ImageChange
  status:
    lastVersion: 4
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 1
    labels:
      app: opennmt-openshift
    name: opennmt-openshift
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: docker-registry.default.svc:5000/vpavlin-sandbox/opennmt-openshift
    tags:
    - items:
      tag: latest
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: opennmt-openshift
    name: python-36-centos7
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: centos/python-36-centos7
      from:
        kind: DockerImage
        name: centos/python-36-centos7
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata: 
    name: opennmt
    annotations:
      volume.beta.kubernetes.io/storage-class: ceph-dyn-datahub-paas
    labels:
      app: opennmt-openshift
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
